# Utilisez une image de base avec Python
FROM python:3.8

ENV PYTHONUNBUFFERED=1

# Copiez le script Python dans l'image
COPY 2_redis_sync.py /app2/2_redis_sync.py

# Installez les dépendances
RUN pip install redis pika 
 
# Définissez le répertoire de travail
WORKDIR /app2

# Définissez la commande à exécuter lors du lancement de l'image
ENTRYPOINT python -u 2_redis_sync.py

